### PR TITLE
Fix Doesn't fingerprint URLs with spaces encoded as %20

### PR DESCRIPTION
**Pull request by ky940819**
This fixes issue #9

### CODE REVIEW

**Comment by hg515303** [comment]
Verified:
 - Links to files with spaces already encoded in the href/src are maintained as-is and the link is fingerprinted
 - Links to files with spaces in their href/src are have the spaces encoded, and the link is fingerprinted

Approved for deployment -- Hugh

**Comment by hg515303** [comment]
Verified:
 - Spaces and/or encoded spaces are displayed as encoded spaces in source, and the image renders correctly.

Approved for deployment -- Hugh

**Comment by hg515303** [comment]
See preceding comment

Approved for deployment -- Hugh

**Comment by ky940819** [comment]
fixes #9

**Comment by ky940819** [comment]
closes #9

**Pull request merged**
